name: Personal Portfolio Secrets and Environmental Variables

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env: REACT_APP_SERVICE_ID = ${{ secrets.REACT_APP_SERVICE_ID }}
      REACT_APP_TEMPLATE_ID = ${{ secrets.REACT_APP_TEMPLATE_ID }}
      REACT_APP_PUBLIC_KEY = ${{ secrets.REACT_APP_PUBLIC_KEY }}
